library(rjson)

dist = rnorm(1000, 3, 2)
jsoned <- toJSON(dist)
write.table(jsoned, './norm_dist1.json', row.names = FALSE, col.names = FALSE, quote = FALSE)
png(file = "./norm_dist1.png")
hist(dist, main = "Normal Distribution")
dev.off()

# dist = runif(1000, 0.23, 10.89)
# jsoned <- toJSON(dist)
# write.table(jsoned, './unif_dist1.json', row.names = FALSE, col.names = FALSE, quote = FALSE)
# png(file = "unif_dist1.png")
# hist(dist, main = "Uniform Distribution")
# dev.off()

# dist = rexp(1000, 3);
# jsoned <- toJSON(dist)
# write.table(jsoned, './exp_dist1.json', row.names = FALSE, col.names = FALSE, quote = FALSE)
# png(file = "exp_dist1.png")
# hist(dist, main = "Exponential Distribution")
# dev.off()

# dist = rlnorm(1000, 0.33, 0.66)
# jsoned <- toJSON(dist)
# write.table(jsoned, './lgnorm_dist1.json', row.names = FALSE, col.names = FALSE, quote = FALSE)
# png(file = "./lgnorm_dist1.png")
# hist(dist, main = "Log-Normal Distribution")
# dev.off()

# library(triangle)
# dist = rtriangle(1000, 2, 15, 4)
# jsoned <- toJSON(dist)
# write.table(jsoned, './tri_dist1.json', row.names = FALSE, col.names = FALSE, quote = FALSE)
# png(file = "./tri_dist1.png")
# hist(dist, main = "Triangle Distribution")
# dev.off()